services:
  front-end:
    build: "."
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - web-root:/app/dist/
    develop:
      watch:
        - path: "."
          target: "/app/"
          action: sync
        - path: package.json
          action: rebuild
        - path: ./nginx-conf/nginx.conf
          target: /etc/nginx/conf.d/nginx.conf
          action: sync+restart

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - front-end
    networks:
      - app-network

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --agree-tos --no-eff-email --staging -d jobbishop.jobs  -d www.jobbishop.jobs --register-unsafely-without-email

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge
