services:
  back-end:
    build:
      context: .
      target: dev
    environment:
      - "PORT=5000"
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    networks:
      - db-network
    depends_on:
      - database
